#!/usr/bin/env python

import gtk
import gobject
import keybinder

class Clipboard(list):
    def move_to_last(self, item):
        tmp = self.pop(item)
        self.append(tmp)
        return tmp

    def append(self, item):
        if item in self:
            self.move_to_last(self.index(item))
        else:
            if len(self) > 5:
                del self[0]
            super(Clipboard, self).append(item)

class Pasta:
    def __init__(self):
        self.gtk_clip = gtk.Clipboard()
        self.pasta_clip = Clipboard()
        self.gtk_clip.connect("owner-change", self.change)

        self.model = gtk.ListStore(str)

        self.model.append(['Welcome to Pasta'])
        self.model.append(['Pasta is a minimal clipboard-manager'])
        self.model.append(['select a line and press Enter\nto store it on your clipboard'])

        self.window = gtk.Window()
        self.window.stick()
        self.window.set_resizable(False)
        self.window.set_skip_pager_hint(True)
        self.window.set_skip_taskbar_hint(True)
        self.window.set_position(gtk.WIN_POS_CENTER)
        self.window.set_decorated(False)
        self.window.set_keep_above(True)
        self.tree = gtk.TreeView(self.model)

        
        self.cell = gtk.CellRendererText()
        self.column = gtk.TreeViewColumn()
        self.column.pack_start(self.cell)
        self.column.set_attributes(self.cell, text=0)
        self.column.set_title('Pasta')
        self.tree.append_column(self.column)

        self.window.add(self.tree)
        self.tree.show()
        self.window.connect('key-press-event', self.hide)
        self.tree.connect("select-cursor-row", self.select)
    
    def hide(self, widget, data=None):
        key = gtk.gdk.keyval_name(data.keyval)
        if key == 'Escape':
            self.window.hide()
    
    def change(self, widget, data=None):
        text = self.get_gtk_clip()
        if text:
            self.pasta_clip.append(text)
            self.model.clear()
            for i in reversed(self.pasta_clip):
                self.model.append([i])
            self.window.hide()
    
    def get_gtk_clip(self):
        return self.gtk_clip.wait_for_text()
    
    def set_gtk_clip(self, text):
        self.gtk_clip.set_text(text)
        self.gtk_clip.store()
    
    def select(self, widget, data=None):
        sel = self.tree.get_selection()
        model, iter = sel.get_selected()
        self.set_gtk_clip(model.get_value(iter, 0))

    def show(self):
        gobject.timeout_add(100, self.present)

    def present(self):
        self.window.present()
        selection = self.tree.get_selection()
        selection.select_path(0)
    
if __name__ == "__main__":
    pasta = Pasta()
    keybinder.bind("<Control><Shift>V", lambda: pasta.show())
    gtk.main()

